// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package psql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID         int32            `json:"id"`
	CustomerID pgtype.Int4      `json:"customer_id"`
	Chat       pgtype.Text      `json:"chat"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}

type Customer struct {
	ID             int32            `json:"id"`
	FirstName      string           `json:"first_name"`
	LastName       string           `json:"last_name"`
	Email          pgtype.Text      `json:"email"`
	PhoneNumber    pgtype.Text      `json:"phone_number"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	LastModifiedAt pgtype.Timestamp `json:"last_modified_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
}

type Product struct {
	ID             int32            `json:"id"`
	Name           string           `json:"name"`
	Description    pgtype.Text      `json:"description"`
	Price          pgtype.Numeric   `json:"price"`
	Category       pgtype.Text      `json:"category"`
	Brand          pgtype.Text      `json:"brand"`
	Stock          int32            `json:"stock"`
	ImageUrl       pgtype.Text      `json:"image_url"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	LastModifiedAt pgtype.Timestamp `json:"last_modified_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
}

type Review struct {
	ID             int32            `json:"id"`
	ProductID      pgtype.Int4      `json:"product_id"`
	CustomerID     pgtype.Int4      `json:"customer_id"`
	Rating         int32            `json:"rating"`
	ReviewText     pgtype.Text      `json:"review_text"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	LastModifiedAt pgtype.Timestamp `json:"last_modified_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
}
