// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package psql

import (
	"context"
)

type Querier interface {
	InsertReview(ctx context.Context, arg InsertReviewParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
